#!/bin/bash

convert -resize 1200 -quality 90 71-texts.png 71-texts-sm.png
convert -resize 1200 -quality 90 abdandoned.png abdandoned-sm.png
convert -resize 1200 -quality 90 acknowledged.png acknowledged-sm.png
convert -resize 1200 -quality 90 all-hail-peralta.png all-hail-peralta-sm.png
convert -resize 1200 -quality 90 all-hail-terry.png all-hail-terry-sm.png
convert -resize 1200 -quality 90 barrels.png barrels-sm.png
convert -resize 1200 -quality 90 bat-meat.png bat-meat-sm.png
convert -resize 1200 -quality 90 best-at-sex.png best-at-sex-sm.png
convert -resize 1200 -quality 90 best-thing.png best-thing-sm.png
convert -resize 1200 -quality 90 bomb-da-butt.png bomb-da-butt-sm.png
convert -resize 1200 -quality 90 cant-hear.png cant-hear-sm.png
convert -resize 1200 -quality 90 change-good.png change-good-sm.png
convert -resize 1200 -quality 90 church.png church-sm.png
convert -resize 1200 -quality 90 cosplay.png cosplay-sm.png
convert -resize 1200 -quality 90 crossover.png crossover-sm.png
convert -resize 1200 -quality 90 da-bomb.png da-bomb-sm.png
convert -resize 1200 -quality 90 decisions.png decisions-sm.png
convert -resize 1200 -quality 90 doug-hi-five.png doug-hi-five-sm.png
convert -resize 1200 -quality 90 doug-hug.png doug-hug-sm.png
convert -resize 1200 -quality 90 doug-judy-song-1.png doug-judy-song-1-sm.png
convert -resize 1200 -quality 90 doug-judy-song-2.png doug-judy-song-2-sm.png
convert -resize 1200 -quality 90 doug-judy-song-3.png doug-judy-song-3-sm.png
convert -resize 1200 -quality 90 doug-not-alive.png doug-not-alive-sm.png
convert -resize 1200 -quality 90 drink-water.png drink-water-sm.png
convert -resize 1200 -quality 90 drumroll.png drumroll-sm.png
convert -resize 1200 -quality 90 erotic-atmospherer.png erotic-atmospherer-sm.png
convert -resize 1200 -quality 90 feeling-great.png feeling-great-sm.png
convert -resize 1200 -quality 90 fun-office.png fun-office-sm.png
convert -resize 1200 -quality 90 fun-productive.png fun-productive-sm.png
convert -resize 1200 -quality 90 gina-angel-elgort-syndrome.png gina-angel-elgort-syndrome-sm.png
convert -resize 1200 -quality 90 gina-culpa.png gina-culpa-sm.png
convert -resize 1200 -quality 90 gina-hamilton.png gina-hamilton-sm.png
convert -resize 1200 -quality 90 guessing-game.png guessing-game-sm.png
convert -resize 1200 -quality 90 hats.png hats-sm.png
convert -resize 1200 -quality 90 heteronormative.png heteronormative-sm.png
convert -resize 1200 -quality 90 hitchock.png hitchock-sm.png
convert -resize 1200 -quality 90 holt-69.png holt-69-sm.png
convert -resize 1200 -quality 90 holt-babies.png holt-babies-sm.png
convert -resize 1200 -quality 90 holt-baloon-pop.png holt-baloon-pop-sm.png
convert -resize 1200 -quality 90 holt-happy.png holt-happy-sm.png
convert -resize 1200 -quality 90 holt-invigorating.png holt-invigorating-sm.png
convert -resize 1200 -quality 90 holt-kangol-hat.png holt-kangol-hat-sm.png
convert -resize 1200 -quality 90 holt-letter-sms.png holt-letter-sms-sm.png
convert -resize 1200 -quality 90 holt-loopholes.png holt-loopholes-sm.png
convert -resize 1200 -quality 90 holt-smile.png holt-smile-sm.png
convert -resize 1200 -quality 90 holt-straight-face.png holt-straight-face-sm.png
convert -resize 1200 -quality 90 holt-sure.png holt-sure-sm.png
convert -resize 1200 -quality 90 hootless.png hootless-sm.png
convert -resize 1200 -quality 90 how-do-you-feel.png how-do-you-feel-sm.png
convert -resize 1200 -quality 90 i9-c3-g6.png i9-c3-g6-sm.png
convert -resize 1200 -quality 90 intestine.png intestine-sm.png
convert -resize 1200 -quality 90 jake-fronties.png jake-fronties-sm.png
convert -resize 1200 -quality 90 jake-fun.png jake-fun-sm.png
convert -resize 1200 -quality 90 jimmy-jabs.png jimmy-jabs-sm.png
convert -resize 1200 -quality 90 larry.png larry-sm.png
convert -resize 1200 -quality 90 looks-cool.png looks-cool-sm.png
convert -resize 1200 -quality 90 loop-hole.png loop-hole-sm.png
convert -resize 1200 -quality 90 loser.png loser-sm.png
convert -resize 1200 -quality 90 love-laughing.png love-laughing-sm.png
convert -resize 1200 -quality 90 mango-yogurt.png mango-yogurt-sm.png
convert -resize 1200 -quality 90 mumps.png mumps-sm.png
convert -resize 1200 -quality 90 my-sex-tape.png my-sex-tape-sm.png
convert -resize 1200 -quality 90 neat-event.png neat-event-sm.png
convert -resize 1200 -quality 90 no-tears.png no-tears-sm.png
convert -resize 1200 -quality 90 oh-mama.png oh-mama-sm.png
convert -resize 1200 -quality 90 overconfidence-1.png overconfidence-1-sm.png
convert -resize 1200 -quality 90 overconfidence-2.png overconfidence-2-sm.png
convert -resize 1200 -quality 90 overconfidence-3.png overconfidence-3-sm.png
convert -resize 1200 -quality 90 overconfidence-4.png overconfidence-4-sm.png
convert -resize 1200 -quality 90 parlov-dance.png parlov-dance-sm.png
convert -resize 1200 -quality 90 peralta-deniro.png peralta-deniro-sm.png
convert -resize 1200 -quality 90 pimento-eyes.png pimento-eyes-sm.png
convert -resize 1200 -quality 90 pimento-how-are-you.png pimento-how-are-you-sm.png
convert -resize 1200 -quality 90 pimento-kids.png pimento-kids-sm.png
convert -resize 1200 -quality 90 ramen.png ramen-sm.png
convert -resize 1200 -quality 90 razzmatazz.png razzmatazz-sm.png
convert -resize 1200 -quality 90 rosa-blowing.png rosa-blowing-sm.png
convert -resize 1200 -quality 90 rosa-computers-1.png rosa-computers-1-sm.png
convert -resize 1200 -quality 90 rosa-computers-2.png rosa-computers-2-sm.png
convert -resize 1200 -quality 90 rosa-computers-3.png rosa-computers-3-sm.png
convert -resize 1200 -quality 90 rosa-giggles.png rosa-giggles-sm.png
convert -resize 1200 -quality 90 rosa-hand.png rosa-hand-sm.png
convert -resize 1200 -quality 90 rosa-la-la-land.png rosa-la-la-land-sm.png
convert -resize 1200 -quality 90 rosa-love-1.png rosa-love-1-sm.png
convert -resize 1200 -quality 90 rosa-love-2.png rosa-love-2-sm.png
convert -resize 1200 -quality 90 rosa-romcom.png rosa-romcom-sm.png
convert -resize 1200 -quality 90 satisfied.png satisfied-sm.png
convert -resize 1200 -quality 90 shocked.png shocked-sm.png
convert -resize 1200 -quality 90 sleep.png sleep-sm.png
convert -resize 1200 -quality 90 small-talk.png small-talk-sm.png
convert -resize 1200 -quality 90 story-checks-out.png story-checks-out-sm.png
convert -resize 1200 -quality 90 stupidest-thing.png stupidest-thing-sm.png
convert -resize 1200 -quality 90 terry-loved.png terry-loved-sm.png
convert -resize 1200 -quality 90 tip-buds.png tip-buds-sm.png
convert -resize 1200 -quality 90 tip-cut.png tip-cut-sm.png
convert -resize 1200 -quality 90 tips-greg.png tips-greg-sm.png
convert -resize 1200 -quality 90 tips-jake.png tips-jake-sm.png
convert -resize 1200 -quality 90 velvet-thunder-1.png velvet-thunder-1-sm.png
convert -resize 1200 -quality 90 velvet-thunder-2.png velvet-thunder-2-sm.png
convert -resize 1200 -quality 90 vindication.png vindication-sm.png
convert -resize 1200 -quality 90 vulfpeck-99.png vulfpeck-99-sm.png
convert -resize 1200 -quality 90 we-re-gonna-die.png we-re-gonna-die-sm.png
convert -resize 1200 -quality 90 what-is-god.png what-is-god-sm.png
convert -resize 1200 -quality 90 words-have-no-meaning.png words-have-no-meaning-sm.png
convert -resize 1200 -quality 90 yogurt-fridge.png yogurt-fridge-sm.png
convert -resize 1200 -quality 90 you-bitch.png you-bitch-sm.png
